apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: nextheader-acme
spec:
  acme:
    email: admin@nextheader.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: nextheader-acme
    solvers:
    - dns01:
        webhook:
          groupName: acme.nextheader.dev
          solverName: coredns-solver
          config:
            coreDNSPrefix: /skydns
            etcdEndpoints: "http://[2a06:de00:50:1:ff00::11]:2379"
            etcdUsernameRef:
              name: etcd-credentials
              key: etcd-username        
            etcdPasswordRef: 
              name: etcd-credentials
              key: etcd-password