---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: storage-system
spec:
  replica: 1
  selector:
    matchLabels:
      run: postgres
  template:
    metadata:
      labels:
        run: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
      containers:
        - name: postgres
          image: postgres
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-credentials
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: storage-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres.nextheader.dev
    external-dns.alpha.kubernetes.io/ttl: "120"
spec:
  selector:
    run: postgres
  type: LoadBalancer
  ports:
    - port: 5432
      protocol: TCP
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: postgres-policy
  namespace: storage-system
spec:
  selector: run == 'postgres'
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
    protocol: TCP
    destination:
      ports:
        - 5432
  egress:
  - action: Allow