apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring-system
data:
  web-config.yml: |-
    tls_server_config:
      cert_file: /etc/ssl/nginx/tls.crt
      key_file: /etc/ssl/nginx/tls.key
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      scheme: https
      static_configs:
      - targets: ['prometheus.nextheader.dev:443']
    - job_name: "kubernetes-apiservers"
      scheme: http
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels:
          [
            __meta_kubernetes_namespace,
            __meta_kubernetes_service_name,
            __meta_kubernetes_endpoint_port_name,
          ]
        action: keep
        regex: (.+)