apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: dns-system
data:
  Corefile: |
   .:53 {
      log
      errors
      health
      ready
      kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
      }
      hosts /etc/coredns/NodeHosts {
        ttl 60
        reload 15s
        fallthrough
      }
      prometheus :9153
      forward . 2a00:1098:2c::1
      forward . 2a01:4f8:c2c:123f::1
      forward . 2a01:4f9:c010:3f02::1
      cache 30
      loop
      reload
      loadbalance
   }

   nextheader.dev:53 {
      log
      errors
      view etcd {
        expr type() in ['A', 'AAAA', 'TXT']
      }
      etcd {
        endpoint http://[2a06:de00:50:1:ff00::11]:2379
        path /skydns
        credentials {$ETCD_USERNAME} {$ETCD_PASSWORD}
        fallthrough
      }
      forward . [::1]:5353
   }

   nextheader.dev:53 {
      log
      errors
      view etcd {
        expr type() not in ['A', 'AAAA', 'TXT']
      }
      forward . [::1]:5353
   }

   nextheader.dev:5353 {
      log
      errors
      file /etc/coredns/db.nextheader.dev
   }

   as215011.net:53 {
      log
      errors
      view etcd {
        expr type() in ['A', 'AAAA', 'TXT']
      }
      etcd {
        endpoint http://[2a06:de00:50:1:ff00::11]:2379
        path /skydns
        credentials {$ETCD_USERNAME} {$ETCD_PASSWORD}
        fallthrough
      }
      forward . [::1]:5353
   }

   as215011.net:53 {
      log
      errors
      view etcd {
        expr type() not in ['A', 'AAAA', 'TXT']
      }
      forward . [::1]:5353
   }

   as215011.net:5353 {
      log
      errors
      file /etc/coredns/db.as215011.net
   }

  db.nextheader.dev: |
   nextheader.dev.              IN    SOA   ns0.nextheader.dev. ns1.nextheader.dev. (
            2003080800 ; sn = serial number
            172800     ; ref = refresh = 2d
            900        ; ret = update retry = 15m
            1209600    ; ex = expiry = 2w
            3600       ; nx = nxdomain ttl = 1h
            )
   @                            IN          NS          ns0.nextheader.dev.
   @                            IN          NS          ns1.nextheader.dev.
   ns0.nextheader.dev.          IN          AAAA        2a06:de00:50:1:ff00::10
   ns1.nextheader.dev.          IN          AAAA        2a06:de00:50:1:ff00::10

  db.as215011.net: |
   as215011.net.              IN    SOA   ns0.as215011.net. ns1.as215011.net. (
            2003080800 ; sn = serial number
            172800     ; ref = refresh = 2d
            900        ; ret = update retry = 15m
            1209600    ; ex = expiry = 2w
            3600       ; nx = nxdomain ttl = 1h
            )
   @                            IN          NS          ns0.as215011.net.
   @                            IN          NS          ns1.as215011.net.
   ns0.as215011.net.            IN          AAAA        2a06:de00:50:1:ff00::10
   ns1.as215011.net.            IN          AAAA        2a06:de00:50:1:ff00::10

  NodeHosts: |
   2a06:de00:50:ffff:ffff::191 core