apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns
  namespace: dns-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: coredns
rules:
  - apiGroups: [""]
    resources: ["endpoints", "services", "pods", "namespaces"]
    verbs: ["list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: coredns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coredns
subjects:
- kind: ServiceAccount
  name: coredns
  namespace: dns-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: dns-system
  labels:
    k8s-app: coredns
    app.kubernetes.io/name: coredns
    kubernetes.io/name: CoreDNS
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns
      app.kubernetes.io/name: coredns
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        app.kubernetes.io/name: coredns
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: coredns
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
      affinity:
         podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
           - labelSelector:
               matchExpressions:
               - key: k8s-app
                 operator: In
                 values: ["kube-dns"]
             topologyKey: kubernetes.io/hostname
      containers:
      - name: coredns
        image: coredns/coredns:latest
        imagePullPolicy: IfNotPresent
        args:
          - -conf
          - /etc/coredns/Corefile
        volumeMounts:
        - mountPath: /etc/coredns
          name: config-volume
          readOnly: true
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9153
          name: metrics
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
        env:
        - name: ETCD_USERNAME
          valueFrom:
            secretKeyRef:
              name: etcd-credentials
              key: etcd-username
        - name: ETCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: etcd-credentials
              key: etcd-password
      dnsPolicy: Default
      volumes:
      - name: config-volume
        configMap:
          name: coredns
          items:
          - key: Corefile
            path: Corefile
          - key: NodeHosts
            path: NodeHosts
          - key: db.nextheader.dev
            path: db.nextheader.dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: dns-system
data:
  Corefile: |
   .:53 {
      log
      errors
      health
      ready
      kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
      }
      hosts /etc/coredns/NodeHosts {
        ttl 60
        reload 15s
        fallthrough
      }
      prometheus :9153
      forward . 2a00:1098:2c::1
      forward . 2a01:4f8:c2c:123f::1
      forward . 2a01:4f9:c010:3f02::1
      cache 30
      loop
      reload
      loadbalance
   }

   nextheader.dev:53 {
      log
      errors
      view etcd {
        expr type() in ['A', 'AAAA', 'TXT']
      }
      etcd {
        endpoint http://[2a06:de00:50:1:ff00::11]:2379
        path /skydns
        credentials {$ETCD_USERNAME} {$ETCD_PASSWORD}
        fallthrough
      }
      forward . [::1]:5353
   }

   nextheader.dev:53 {
      log
      errors
      view etcd {
        expr type() not in ['A', 'AAAA', 'TXT']
      }
      forward . [::1]:5353
   }

   nextheader.dev:5353 {
      log
      errors
      file /etc/coredns/db.nextheader.dev
   }

  NodeHosts: |
   2a06:de00:50:ffff:ffff::191 core

  db.nextheader.dev: |
   nextheader.dev.              IN    SOA   ns0.nextheader.dev. ns1.nextheader.dev. (
            2003080800 ; sn = serial number
            172800     ; ref = refresh = 2d
            900        ; ret = update retry = 15m
            1209600    ; ex = expiry = 2w
            3600       ; nx = nxdomain ttl = 1h
            )
   @                            IN          NS          ns0.nextheader.dev.
   @                            IN          NS          ns1.nextheader.dev.
   ns0.nextheader.dev.          IN          AAAA        2a06:de00:50:1:ff00::10
   ns1.nextheader.dev.          IN          AAAA        2a06:de00:50:1:ff00::10
---
apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: dns-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
spec:
  selector:
    k8s-app: kube-dns
  type: ClusterIP
  clusterIP: 2a06:de00:50:1:ff00::10
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP