apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: dns-system
spec:
  selector:
    matchLabels:
      run: etcd
  replicas: 1
  template:
    metadata:
      labels:
        run: etcd
    spec:
      containers:
      - name: etcd
        image: bitnami/etcd:latest
        ports:
        - containerPort: 2379
        env:
        - name: ETCD_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: etcd-credentials
              key: etcd-password
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: dns-system
spec:
  selector:
    run: etcd
  type: ClusterIP
  clusterIP: 2a06:de00:50:1:ff00::11
  ports:
  - port: 2379
    protocol: TCP